Add github action to build and publish docker images on new releases
crate/crate-operator pull request #106
Opened 2020-11-11 08:12 UTC by Taliik

## Summary of the changes / Why this is an improvement
This github action will trigger when a new tag is release and will build/publish/tag the docker image accordingly.

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2020-11-11 08:20 UTC, chaudum commented on .github/workflows/docker_image.yaml
> +        uses: elgohr/Publish-Docker-Github-Action@master
I would nail the version to the current latests (2.22)

```suggestion
        uses: elgohr/Publish-Docker-Github-Action@2.22
```

https://github.com/marketplace/actions/publish-docker?version=2.22

2020-11-11 08:20 UTC, chaudum commented on .github/workflows/docker_image.yaml
> +      - uses: actions/checkout@v2
Maybe also give the step a human readable name

2020-11-11 08:57 UTC, chaudum approved these changes

2020-11-11 08:57 UTC, chaudum commented on .github/workflows/docker_image.yaml
> +name: Build and publish docker image to docker hub
```suggestion
name: Build and publish Docker image to Docker Hub
```

2020-11-11 09:01 UTC, MarkusH requested changes
I'm not entirely sure from the changes which registry is going to be used. Is it Dockerhub? GitHub?

I think extending the installation instructions to include the corresponding `docker run` or snippet for a Kubernetes `Deployment` would be useful. At least to see what/how/where the image is and how it's referenced.

Please prefix the commit message with `Fix #75` to reference the commit and issue.

2020-11-12 09:33 UTC, chaudum approved these changes

2020-11-12 09:33 UTC, chaudum commented on .github/workflows/docker_image.yaml
> +        uses: actions/checkout@v2
I would prefer if we use the formatting we otherwise have as well.

```suggestion
      - name: Checkout
        uses: actions/checkout@v2
```

2020-11-12 09:33 UTC, chaudum commented on .github/workflows/docker_image.yaml
> +  multi:
I would name the job more specific, e.g. `docker`

2020-11-12 09:43 UTC, chaudum approved these changes

2020-11-12 09:49 UTC, MarkusH approved these changes

2020-11-12 09:51 UTC, merged