Add ReadTheDocs config
crate/crate-operator pull request #77
Opened 2020-09-28 18:13 UTC by MarkusH

## Summary of the changes / Why this is an improvement

This change adds a first integration of the builds into ReadTheDocs. From there we can take it to the next level and integrate it into Crate.io's documentation framework.

A demo build is on https://crate-operator.readthedocs.io/en/mh-rtd-config/

## Checklist

 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2020-09-29 16:26 UTC, mechanomi requested changes
please use the standard config found here: https://github.com/crate/crate-docs/blob/master/.readthedocs.yml

2020-09-30 10:34 UTC, mechanomi commented
sorry, just to clarify. I missed that the current package has to be installed. the best way to do that is to add "." to the requirements file. see here: https://github.com/crate/crate-docs-theme/blob/master/docs/requirements.txt

(changing the python version is fine)

2020-09-30 11:10 UTC, MarkusH commented
Thanks @mechanomi I've update the RTD config and also had to make sure that the API docs are build accordingly.

2020-10-02 10:32 UTC, mechanomi approved these changes

2020-10-02 10:38 UTC, merged